---
name: sonar-release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      releaseId:
        type: string
        description: Release ID
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false
        required: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@8974b5c27a786cdf7bba286a2fff5d12a2f7d78a # 7.2.0
    with:
      version: ${{ inputs.version }}
      releaseId: ${{ inputs.releaseId }}
      dryRun: ${{ inputs.dryRun || false }}
      publishToBinaries: true
      mavenCentralSync: true
      slackChannel: ask-squad-web
